// Country data: 60+ countries with positions for equirectangular world map (1000x500)
// lat/lon converted to canvas coords: x=(lon+180)/360*1000, y=(90-lat)/180*500
module.exports = {
  countries: [
    // North America
    { id: 'USA', name: 'Estados Unidos',  flag: '🇺🇸', x: 250, y: 175, region: 'NA' },
    { id: 'CAN', name: 'Canada',           flag: '🇨🇦', x: 270, y: 130, region: 'NA' },
    { id: 'MEX', name: 'Mexico',           flag: '🇲🇽', x: 245, y: 215, region: 'NA' },
    { id: 'CUB', name: 'Cuba',             flag: '🇨🇺', x: 290, y: 220, region: 'NA' },

    // South America
    { id: 'BRA', name: 'Brasil',           flag: '🇧🇷', x: 350, y: 320, region: 'SA' },
    { id: 'ARG', name: 'Argentina',        flag: '🇦🇷', x: 330, y: 380, region: 'SA' },
    { id: 'CHL', name: 'Chile',            flag: '🇨🇱', x: 315, y: 380, region: 'SA' },
    { id: 'PER', name: 'Peru',             flag: '🇵🇪', x: 305, y: 320, region: 'SA' },
    { id: 'COL', name: 'Colombia',         flag: '🇨🇴', x: 305, y: 270, region: 'SA' },
    { id: 'VEN', name: 'Venezuela',        flag: '🇻🇪', x: 320, y: 260, region: 'SA' },
    { id: 'URY', name: 'Uruguay',          flag: '🇺🇾', x: 345, y: 380, region: 'SA' },
    { id: 'BOL', name: 'Bolivia',          flag: '🇧🇴', x: 325, y: 335, region: 'SA' },

    // Europe
    { id: 'GBR', name: 'Reino Unido',      flag: '🇬🇧', x: 485, y: 145, region: 'EU' },
    { id: 'FRA', name: 'Francia',          flag: '🇫🇷', x: 495, y: 165, region: 'EU' },
    { id: 'DEU', name: 'Alemania',         flag: '🇩🇪', x: 510, y: 155, region: 'EU' },
    { id: 'ITA', name: 'Italia',           flag: '🇮🇹', x: 515, y: 180, region: 'EU' },
    { id: 'ESP', name: 'Espana',           flag: '🇪🇸', x: 485, y: 185, region: 'EU' },
    { id: 'POL', name: 'Polonia',          flag: '🇵🇱', x: 525, y: 155, region: 'EU' },
    { id: 'UKR', name: 'Ucrania',          flag: '🇺🇦', x: 545, y: 165, region: 'EU' },
    { id: 'ROU', name: 'Rumania',          flag: '🇷🇴', x: 535, y: 175, region: 'EU' },
    { id: 'NLD', name: 'Holanda',          flag: '🇳🇱', x: 500, y: 150, region: 'EU' },
    { id: 'BEL', name: 'Belgica',          flag: '🇧🇪', x: 498, y: 158, region: 'EU' },
    { id: 'PRT', name: 'Portugal',         flag: '🇵🇹', x: 478, y: 185, region: 'EU' },
    { id: 'GRC', name: 'Grecia',           flag: '🇬🇷', x: 535, y: 190, region: 'EU' },
    { id: 'NOR', name: 'Noruega',          flag: '🇳🇴', x: 510, y: 110, region: 'EU' },
    { id: 'SWE', name: 'Suecia',           flag: '🇸🇪', x: 520, y: 115, region: 'EU' },
    { id: 'FIN', name: 'Finlandia',        flag: '🇫🇮', x: 535, y: 110, region: 'EU' },
    { id: 'CHE', name: 'Suiza',            flag: '🇨🇭', x: 505, y: 170, region: 'EU' },
    { id: 'AUT', name: 'Austria',          flag: '🇦🇹', x: 515, y: 168, region: 'EU' },
    { id: 'CZE', name: 'Republica Checa',  flag: '🇨🇿', x: 518, y: 160, region: 'EU' },
    { id: 'HUN', name: 'Hungria',          flag: '🇭🇺', x: 525, y: 168, region: 'EU' },
    { id: 'SRB', name: 'Serbia',           flag: '🇷🇸', x: 528, y: 178, region: 'EU' },
    { id: 'IRL', name: 'Irlanda',          flag: '🇮🇪', x: 475, y: 145, region: 'EU' },
    { id: 'DNK', name: 'Dinamarca',        flag: '🇩🇰', x: 510, y: 140, region: 'EU' },

    // Russia / Central Asia
    { id: 'RUS', name: 'Rusia',            flag: '🇷🇺', x: 620, y: 130, region: 'AS' },
    { id: 'KAZ', name: 'Kazajistan',       flag: '🇰🇿', x: 620, y: 165, region: 'AS' },
    { id: 'TUR', name: 'Turquia',          flag: '🇹🇷', x: 555, y: 185, region: 'AS' },

    // Middle East
    { id: 'IRN', name: 'Iran',             flag: '🇮🇷', x: 590, y: 195, region: 'ME' },
    { id: 'IRQ', name: 'Irak',             flag: '🇮🇶', x: 575, y: 195, region: 'ME' },
    { id: 'SAU', name: 'Arabia Saudita',   flag: '🇸🇦', x: 575, y: 215, region: 'ME' },
    { id: 'ISR', name: 'Israel',           flag: '🇮🇱', x: 560, y: 200, region: 'ME' },
    { id: 'SYR', name: 'Siria',            flag: '🇸🇾', x: 565, y: 190, region: 'ME' },
    { id: 'YEM', name: 'Yemen',            flag: '🇾🇪', x: 580, y: 235, region: 'ME' },
    { id: 'JOR', name: 'Jordania',         flag: '🇯🇴', x: 562, y: 205, region: 'ME' },
    { id: 'ARE', name: 'Emiratos',         flag: '🇦🇪', x: 590, y: 220, region: 'ME' },
    { id: 'AFG', name: 'Afganistan',       flag: '🇦🇫', x: 605, y: 190, region: 'ME' },
    { id: 'PAK', name: 'Pakistan',         flag: '🇵🇰', x: 615, y: 200, region: 'AS' },

    // Asia
    { id: 'CHN', name: 'China',            flag: '🇨🇳', x: 690, y: 175, region: 'AS' },
    { id: 'IND', name: 'India',            flag: '🇮🇳', x: 645, y: 215, region: 'AS' },
    { id: 'JPN', name: 'Japon',            flag: '🇯🇵', x: 760, y: 175, region: 'AS' },
    { id: 'KOR', name: 'Corea del Sur',    flag: '🇰🇷', x: 740, y: 175, region: 'AS' },
    { id: 'PRK', name: 'Corea del Norte',  flag: '🇰🇵', x: 738, y: 168, region: 'AS' },
    { id: 'VNM', name: 'Vietnam',          flag: '🇻🇳', x: 705, y: 220, region: 'AS' },
    { id: 'THA', name: 'Tailandia',        flag: '🇹🇭', x: 695, y: 225, region: 'AS' },
    { id: 'IDN', name: 'Indonesia',        flag: '🇮🇩', x: 720, y: 270, region: 'AS' },
    { id: 'MYS', name: 'Malasia',          flag: '🇲🇾', x: 705, y: 250, region: 'AS' },
    { id: 'PHL', name: 'Filipinas',        flag: '🇵🇭', x: 740, y: 235, region: 'AS' },
    { id: 'TWN', name: 'Taiwan',           flag: '🇹🇼', x: 730, y: 205, region: 'AS' },
    { id: 'MNG', name: 'Mongolia',         flag: '🇲🇳', x: 680, y: 150, region: 'AS' },
    { id: 'BGD', name: 'Bangladesh',       flag: '🇧🇩', x: 670, y: 215, region: 'AS' },

    // Africa
    { id: 'EGY', name: 'Egipto',           flag: '🇪🇬', x: 545, y: 215, region: 'AF' },
    { id: 'LBY', name: 'Libia',            flag: '🇱🇾', x: 525, y: 215, region: 'AF' },
    { id: 'DZA', name: 'Argelia',          flag: '🇩🇿', x: 500, y: 210, region: 'AF' },
    { id: 'MAR', name: 'Marruecos',        flag: '🇲🇦', x: 480, y: 205, region: 'AF' },
    { id: 'TUN', name: 'Tunez',            flag: '🇹🇳', x: 515, y: 200, region: 'AF' },
    { id: 'NGA', name: 'Nigeria',          flag: '🇳🇬', x: 510, y: 260, region: 'AF' },
    { id: 'ETH', name: 'Etiopia',          flag: '🇪🇹', x: 555, y: 250, region: 'AF' },
    { id: 'KEN', name: 'Kenia',            flag: '🇰🇪', x: 555, y: 280, region: 'AF' },
    { id: 'ZAF', name: 'Sudafrica',        flag: '🇿🇦', x: 535, y: 350, region: 'AF' },
    { id: 'SDN', name: 'Sudan',            flag: '🇸🇩', x: 545, y: 245, region: 'AF' },
    { id: 'COD', name: 'Congo',            flag: '🇨🇩', x: 530, y: 290, region: 'AF' },
    { id: 'AGO', name: 'Angola',           flag: '🇦🇴', x: 515, y: 315, region: 'AF' },
    { id: 'GHA', name: 'Ghana',            flag: '🇬🇭', x: 495, y: 265, region: 'AF' },

    // Oceania
    { id: 'AUS', name: 'Australia',        flag: '🇦🇺', x: 760, y: 330, region: 'OC' },
    { id: 'NZL', name: 'Nueva Zelanda',    flag: '🇳🇿', x: 800, y: 370, region: 'OC' },
  ],

  // Approximate neighbor relationships (used for movement/invasion)
  neighbors: {
    USA: ['CAN','MEX','CUB'],
    CAN: ['USA'],
    MEX: ['USA','CUB'],
    CUB: ['USA','MEX'],
    BRA: ['ARG','PER','COL','VEN','URY','BOL'],
    ARG: ['BRA','CHL','URY','BOL'],
    CHL: ['ARG','PER','BOL'],
    PER: ['BRA','CHL','COL','BOL'],
    COL: ['BRA','PER','VEN'],
    VEN: ['BRA','COL'],
    URY: ['BRA','ARG'],
    BOL: ['BRA','ARG','CHL','PER'],
    GBR: ['IRL','FRA','NLD'],
    FRA: ['GBR','DEU','ITA','ESP','BEL','CHE'],
    DEU: ['FRA','POL','NLD','BEL','CHE','AUT','CZE','DNK'],
    ITA: ['FRA','CHE','AUT','GRC'],
    ESP: ['FRA','PRT'],
    POL: ['DEU','UKR','CZE','RUS'],
    UKR: ['POL','ROU','RUS','HUN'],
    ROU: ['UKR','HUN','SRB'],
    NLD: ['GBR','DEU','BEL'],
    BEL: ['FRA','DEU','NLD'],
    PRT: ['ESP'],
    GRC: ['ITA','TUR','SRB'],
    NOR: ['SWE','FIN'],
    SWE: ['NOR','FIN','DNK'],
    FIN: ['NOR','SWE','RUS'],
    CHE: ['FRA','DEU','ITA','AUT'],
    AUT: ['DEU','ITA','CZE','HUN','CHE'],
    CZE: ['DEU','POL','AUT'],
    HUN: ['UKR','ROU','AUT','SRB'],
    SRB: ['ROU','HUN','GRC'],
    IRL: ['GBR'],
    DNK: ['DEU','SWE'],
    RUS: ['FIN','POL','UKR','KAZ','MNG','CHN','PRK'],
    KAZ: ['RUS','CHN','MNG'],
    TUR: ['GRC','SYR','IRQ','IRN'],
    IRN: ['TUR','IRQ','AFG','PAK','SAU','ARE'],
    IRQ: ['TUR','IRN','SYR','SAU','JOR'],
    SAU: ['IRQ','IRN','JOR','YEM','ARE','EGY'],
    ISR: ['SYR','JOR','EGY'],
    SYR: ['TUR','IRQ','ISR','JOR','LBY'],
    YEM: ['SAU','ARE'],
    JOR: ['IRQ','SAU','ISR','SYR','EGY'],
    ARE: ['SAU','IRN','YEM'],
    AFG: ['IRN','PAK'],
    PAK: ['IRN','AFG','IND','CHN'],
    CHN: ['RUS','KAZ','MNG','PRK','VNM','IND','PAK','BGD','TWN'],
    IND: ['PAK','CHN','BGD'],
    JPN: ['KOR','PRK','TWN'],
    KOR: ['PRK','JPN'],
    PRK: ['CHN','KOR','RUS'],
    VNM: ['CHN','THA','MYS'],
    THA: ['VNM','MYS'],
    IDN: ['MYS','PHL','AUS'],
    MYS: ['THA','VNM','IDN'],
    PHL: ['IDN','TWN'],
    TWN: ['CHN','JPN','PHL'],
    MNG: ['RUS','CHN','KAZ'],
    BGD: ['IND','CHN'],
    EGY: ['LBY','SDN','ISR','JOR','SAU'],
    LBY: ['EGY','TUN','DZA','SDN','SYR'],
    DZA: ['LBY','MAR','TUN','NGA'],
    MAR: ['DZA','ESP'],
    TUN: ['LBY','DZA','ITA'],
    NGA: ['DZA','GHA','SDN','COD'],
    ETH: ['SDN','KEN','SAU','YEM'],
    KEN: ['ETH','SDN','COD'],
    ZAF: ['AGO','COD'],
    SDN: ['EGY','LBY','ETH','KEN','NGA','COD'],
    COD: ['NGA','SDN','KEN','AGO','ZAF'],
    AGO: ['COD','ZAF'],
    GHA: ['NGA','DZA'],
    AUS: ['IDN','NZL'],
    NZL: ['AUS'],
  }
};
